// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/DGISsoft/DGISback/models"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type AssignUserInput struct {
	UserID   primitive.ObjectID `json:"userId"`
	MarkerID primitive.ObjectID `json:"markerId"`
}

type AuthPayload struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type CreateMarkerInput struct {
	MarkerID string    `json:"markerId"`
	Position []float64 `json:"position"`
	Label    string    `json:"label"`
}

type CreateUserInput struct {
	Login       string          `json:"login"`
	Password    string          `json:"password"`
	Role        models.UserRole `json:"role"`
	FullName    string          `json:"fullName"`
	Building    *string         `json:"building,omitempty"`
	PhoneNumber string          `json:"phoneNumber"`
	TelegramTag string          `json:"telegramTag"`
}

type LoginInput struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NotificationSender struct {
	ID       primitive.ObjectID `json:"id"`
	FullName string             `json:"fullName"`
	Building *string            `json:"building,omitempty"`
}

type Query struct {
}

type RemoveUserInput struct {
	UserID   primitive.ObjectID `json:"userId"`
	MarkerID primitive.ObjectID `json:"markerId"`
}

type SendNotificationInput struct {
	UserIds []primitive.ObjectID     `json:"userIds"`
	Title   string                   `json:"title"`
	Message string                   `json:"message"`
	Type    *models.NotificationType `json:"type,omitempty"`
}

type Subscription struct {
}
