// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
	"github.com/DGISsoft/DGISback/models"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type AddImagesToReportInput struct {
	ReportID              primitive.ObjectID `json:"reportID"`
	ApplicationsImageKeys []string           `json:"applicationsImageKeys,omitempty"`
	InspectionImageKeys   []string           `json:"inspectionImageKeys,omitempty"`
	AdditionalImageKeys   []string           `json:"additionalImageKeys,omitempty"`
}

type AssignUserInput struct {
	UserID   primitive.ObjectID `json:"userId"`
	MarkerID primitive.ObjectID `json:"markerId"`
}

type AuthPayload struct {
	Token string       `json:"token"`
	User  *models.User `json:"user"`
}

type CreateMarkerInput struct {
	MarkerID string    `json:"markerId"`
	Position []float64 `json:"position"`
	Label    string    `json:"label"`
}

type CreateUserInput struct {
	Login       string          `json:"login"`
	Password    string          `json:"password"`
	Role        models.UserRole `json:"role"`
	FullName    string          `json:"fullName"`
	Building    *string         `json:"building,omitempty"`
	PhoneNumber string          `json:"phoneNumber"`
	TelegramTag string          `json:"telegramTag"`
}

type CreateWeeklyReportInput struct {
	Applications string `json:"applications"`
	Inspection   string `json:"inspection"`
	Additional   string `json:"additional"`
}

type ImageData struct {
	Key  string `json:"key"`
	Data string `json:"data"`
	Size int    `json:"size"`
}

type ImageUploadResult struct {
	Key  string `json:"key"`
	Name string `json:"name"`
}

type LoginInput struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

type Mutation struct {
}

type NotificationSender struct {
	ID       primitive.ObjectID `json:"id"`
	FullName string             `json:"fullName"`
	Building *string            `json:"building,omitempty"`
}

type Query struct {
}

type RemoveUserInput struct {
	UserID   primitive.ObjectID `json:"userId"`
	MarkerID primitive.ObjectID `json:"markerId"`
}

type SendNotificationInput struct {
	UserIds []primitive.ObjectID     `json:"userIds"`
	Title   string                   `json:"title"`
	Message string                   `json:"message"`
	Type    *models.NotificationType `json:"type,omitempty"`
}

type Subscription struct {
}

type UploadReportImageInput struct {
	File graphql.Upload `json:"file"`
}
